[tool.poetry]
name = "inside"
version = "0.1.0"
description = ""
authors = ["insolor <insolor@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.95.0"
uvicorn = "^0.20.0"
PyJWT = "^2.4.0"
python-decouple = "^3.8"
SQLAlchemy = "^2.0.4"
bcrypt = "^4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.2"
black = "^23.3.0"
isort = "^5.12.0"
requests = "^2.28.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
